# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Win32-UTCFileTime
version:      1.20
version_from: UTCFileTime.pm
installdirs:  site
requires:
    Carp:                          0
    Exporter:                      0
    File::Spec:                    0
    Test:                          0
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
