abstract: Get/set UTC file times with stat/utime on Win32
author: Steve Hay <shay@cpan.org>
build_requires:
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.56
license: perl
name: Win32-UTCFileTime
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 1.00
requires:
  perl: 5.6.0
version: 1.45
