---
abstract: 'Get/set UTC file times with stat/utime on Win32'
author:
  - 'Steve Hay <shay@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  Carp: 0
  Config: 0
  Cwd: 0
  ExtUtils::MakeMaker: 6.42
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Spec::Functions: 0
  FindBin: 0
  Getopt::Long: 0
  Pod::Usage: 0
  Text::Wrap: 0
  strict: 0
  vars: 0
  warnings: 0
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-UTCFileTime
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  XSLoader: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.52
